"""
Amazon Bedrock AI Agent Integration for ScopeGuard.

Demonstrates real-world AI agent tool-use backed by Amazon Bedrock
(e.g., Amazon Nova Micro `amazon.nova-micro-v1:0` or Titan `amazon.titan-text-express-v1`)
routing all tool calls through ScopeGuard.
"""

import json
import logging
from typing import Any
import boto3
import httpx

from agent.tools import TOOL_DEFINITIONS

logger = logging.getLogger("scopeguard.bedrock_agent")


class BedrockAgent:
    """
    AI Agent powered by Amazon Bedrock (Nova Micro / Titan) that executes
    infrastructure tasks with tool-calling intercepted by ScopeGuard.
    """

    def __init__(
        self,
        model_id: str = "amazon.nova-micro-v1:0",
        region_name: str = "us-east-1",
        proxy_url: str = "http://localhost:8000",
        agent_id: str = "bedrock-agent-nova",
    ):
        self.model_id = model_id
        self.region_name = region_name
        self.proxy_url = proxy_url.rstrip("/")
        self.agent_id = agent_id
        self.bedrock_runtime = boto3.client(
            "bedrock-runtime", region_name=self.region_name
        )
        self.http_client = httpx.Client(timeout=30.0)

    def execute_task_with_bedrock(
        self, declared_task: str, session_id: str
    ) -> list[dict[str, Any]]:
        """
        Execute a task using Amazon Bedrock (Nova / Titan) tool-use loop.
        Sends each tool call generated by Bedrock to ScopeGuard proxy.
        """
        logger.info("Invoking Bedrock model %s for task: '%s'", self.model_id, declared_task)

        bedrock_tools = []
        for t in TOOL_DEFINITIONS:
            bedrock_tools.append({
                "toolSpec": {
                    "name": t["name"],
                    "description": t["description"],
                    "inputSchema": {
                        "json": {
                            "type": "object",
                            "properties": {
                                "action": {
                                    "type": "string",
                                    "description": f"Allowed actions: {', '.join(t['actions'][:5])}",
                                },
                                "params": {
                                    "type": "object",
                                    "description": "Action parameters",
                                },
                            },
                            "required": ["action"],
                        }
                    },
                }
            })

        messages = [
            {
                "role": "user",
                "content": [
                    {
                        "text": (
                            f"You are an AI infrastructure agent. Your task is: '{declared_task}'. "
                            "Use the provided tools to perform only the necessary steps for this task."
                        )
                    }
                ],
            }
        ]

        results = []

        try:
            response = self.bedrock_runtime.converse(
                modelId=self.model_id,
                messages=messages,
                inferenceConfig={"maxTokens": 1024, "temperature": 0.0},
                toolConfig={"tools": bedrock_tools},
            )

            output_message = response.get("output", {}).get("message", {})
            content_blocks = output_message.get("content", [])

            for block in content_blocks:
                if "toolUse" in block:
                    tool_use = block["toolUse"]
                    tool_name = tool_use.get("name")
                    input_args = tool_use.get("input", {})
                    action = input_args.get("action", "")
                    params = input_args.get("params", {})

                    # Intercept call via ScopeGuard
                    payload = {
                        "agent_id": self.agent_id,
                        "session_id": session_id,
                        "declared_task": declared_task,
                        "reasoning_excerpt": f"Bedrock tool invoke {tool_name}",
                        "tool_name": tool_name,
                        "tool_action": action,
                        "tool_params": params,
                    }

                    proxy_resp = self.http_client.post(
                        f"{self.proxy_url}/execute-tool", json=payload
                    )
                    res_json = proxy_resp.json()

                    results.append({
                        "task": declared_task,
                        "tool_name": tool_name,
                        "tool_action": action,
                        "decision": res_json.get("decision"),
                        "audit_id": res_json.get("audit_id"),
                        "error": res_json.get("error"),
                    })

        except Exception as e:
            logger.warning("Bedrock invocation note: %s", str(e))
            results.append({"error": str(e)})

        return results
